export const siteConfig = {
  name: "Vivek Purbey | Developer Portfolio",
  authorName: "Vivek Purbey",
  username: "vivi2004",
  description: "Vivek Purbey's portfolio ",
  url: "https://nbarkiya.xyz",
  links: {
    twitter: "https://x.com/VPurbey123",
    github: "https://github.com/vivi2004",
  },
  ogImage: "https://nbarkiya.xyz/profile-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png",
  keywords: [
    "Vivek Purbey",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio  ",
    "React portfolio  ",
    "Developer portfolio  ",
    "Portfolio website  ",
    "Next.js  ",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase  ",
    "Free portfolio  ",
    "Next.js 13  ",
    "Shadcn UI  ",
    "Career timeline  ",
    "Portfolio with dark mode",
    "GitHub portfolio  ",
  ],
};
